# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=50, verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'verbose_name': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=140, verbose_name='Адрес')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьером'), ('indef', 'Неопределен')], max_length=50, verbose_name='Метод доставки')),
                ('date_of', models.TimeField(blank=True, null=True, verbose_name='Время выдачи')),
            ],
            options={
                'verbose_name_plural': 'Доставка',
                'verbose_name': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Номер заявки')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создения')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата модификации')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name_plural': 'Лабораторные заявки',
                'verbose_name': 'Лабораторная заявка',
            },
        ),
        migrations.CreateModel(
            name='MedCenRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Номер заявки')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создения')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата модификации')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name_plural': 'Заявки мед центра',
                'verbose_name': 'Заявка мед центра',
            },
        ),
        migrations.CreateModel(
            name='PrimeMinister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('weight', models.FloatField(verbose_name='Ваш вес')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('salary', models.BigIntegerField(help_text='Пожалуйста, укажите свою реальную зарплату. Так мы сможем решить: сажать или не сажать', verbose_name='Зарплата')),
                ('corrupka', models.BooleanField(db_column='is_corruption', verbose_name='Вы коррупционер?')),
                ('ip', models.GenericIPAddressField(help_text='Лучше сами введите. Все равно вычислим', verbose_name='Ваш IP адрес')),
            ],
        ),
        migrations.CreateModel(
            name='ReqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=240, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.AddField(
            model_name='medcenrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.ReqCategory'),
        ),
        migrations.AddField(
            model_name='medcenrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Client'),
        ),
        migrations.AddField(
            model_name='medcenrequest',
            name='req_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Delivery'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.ReqCategory'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Client'),
        ),
        migrations.CreateModel(
            name='XMLClient',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dispatcher.client',),
        ),
    ]
